"""Explicit per-capital backtest for the body-narrative long-short basket.

Convention:
  - $1 of capital is allocated total.
  - Each month a new long-short basket position is opened.
  - The new position is sized at 1/N of total capital, where N is the
    average number of overlapping positions (90/21 ≈ 4.3 trading-day months).
    Equivalent industry convention: at each entry the strategy deploys
    cash_balance / (max_overlap_remaining).
  - Each position is held for ninety trading days, then closes and the
    capital plus 90-day excess return is returned to cash.
  - Monthly equal-weight allocation across currently-open positions (so
    capital that is "between positions" earns no return).

Benchmarks plotted on the same $1-capital cumulative growth basis:
  - SPDR S&P 500 ETF (SPY) buy-and-hold: $1 invested 2014-01, held through
    2024-12, no rebalance.
  - Fama-French Mkt-RF cumulative: $1 invested 2014-01, monthly compounded
    at the FF Mkt-RF + RF rate.

Output:
  data/per_capital_backtest.jsonl    monthly capital balance per series
  reports/per-capital-backtest.json  terminal values + Sharpe

The figure (figures/fig1_cumulative_pnl.png) is regenerated by
scripts/make-paper-figures.py from these series.
"""
from __future__ import annotations

import json
from pathlib import Path

import numpy as np

REPO = Path(__file__).resolve().parents[1]
DATA = REPO / "data"
REPORTS = REPO / "reports"

TC_BPS_RT = 15.0  # 15 bp round-trip per entry


def _load_strategy_monthly_pct() -> dict[str, float]:
    """Monthly net long-short return (in percent) on the body-narrative
    basket, PIT acceptance anchor, 90-day forward window."""
    rows = [json.loads(l) for l in (DATA / "net_sharpe_strategy_d_pit.jsonl").open(encoding="utf-8")]
    rows = [r for r in rows if r["window_days"] == 90]
    rows.sort(key=lambda r: r["year_month"])
    return {r["year_month"]: r["long_short_pct"] - TC_BPS_RT / 100.0 for r in rows}


def _load_ff_monthly() -> dict[str, dict[str, float]]:
    rows = [json.loads(l) for l in (DATA / "ff5_umd_monthly.jsonl").open(encoding="utf-8")]
    return {r["year_month"]: r for r in rows}


def _load_spy_daily() -> tuple[list[str], list[float]]:
    rows = [json.loads(l) for l in (DATA / "yfinance_cache" / "SPY.jsonl").open(encoding="utf-8")]
    rows.sort(key=lambda r: r["date"])
    return [r["date"] for r in rows], [float(r["close"]) for r in rows]


def per_capital_simulation(monthly_pct: dict[str, float], overlap: int = 4) -> tuple[list[str], list[float]]:
    """Explicit $1-capital backtest.

    At month t, open a new long-short position sized at 1/overlap of the
    current capital. Each position is held for `overlap` months (proxy for
    90 trading days ≈ 4.3 calendar months) and returns capital * (1 + r/100)
    where r is the recorded 90-day forward percentage return.

    State: a FIFO of (open_month, deployed_capital) tuples; on each step,
    close the oldest position if it has aged `overlap` months and refund
    deployed_capital * (1 + r).
    """
    months_sorted = sorted(monthly_pct.keys())
    capital = 1.0
    open_positions: list[tuple[int, float, float]] = []  # (close_step, deployed_capital, position_return_pct)
    capital_path: list[tuple[str, float]] = []

    for step, ym in enumerate(months_sorted):
        # Close any positions that have aged `overlap` steps.
        still_open = []
        for close_step, deployed, ret_pct in open_positions:
            if close_step == step:
                refund = deployed * (1.0 + ret_pct / 100.0)
                capital += refund
            else:
                still_open.append((close_step, deployed, ret_pct))
        open_positions = still_open

        # Open a new position. Size it at 1/overlap of currently-available
        # cash (the cash that is not already deployed to an open position).
        # Since cash_balance is `capital` (all refunded), and we want to
        # spread it across the next `overlap` entries, deploy
        # 1/overlap of the *remaining slots* worth of capital.
        n_open = len(open_positions)
        slots_remaining = overlap - n_open
        if slots_remaining <= 0:
            slots_remaining = 1
        deploy_size = capital / slots_remaining
        ret_pct = monthly_pct[ym]
        capital -= deploy_size
        open_positions.append((step + overlap, deploy_size, ret_pct))

        # Mark-to-market: count cash + open positions' mark-to-cost
        # (we use cost rather than mark-to-market intra-position because
        # the recorded ret_pct is the realized close-to-close 90-day return
        # and is only known at the close)
        total = capital + sum(d for _, d, _ in open_positions)
        capital_path.append((ym, total))

    # Drain remaining open positions at the end
    for close_step, deployed, ret_pct in open_positions:
        capital += deployed * (1.0 + ret_pct / 100.0)
    # Add a final entry past the last month showing the closed-out total
    capital_path.append((months_sorted[-1] + "_close", capital))
    return [m for m, _ in capital_path], [c for _, c in capital_path]


def spy_unit_capital_path(months: list[str]) -> tuple[list[str], list[float]]:
    """$1 of SPY bought at the start of `months` and held; report
    capital path at each month-end. Uses daily SPY closes."""
    dates, closes = _load_spy_daily()
    by_month_last_close: dict[str, float] = {}
    for d, c in zip(dates, closes):
        by_month_last_close[d[:7]] = c

    start_close = None
    for ym in sorted(months):
        if ym in by_month_last_close:
            start_close = by_month_last_close[ym]
            break
    if start_close is None or start_close <= 0:
        return [], []

    out_months = []
    out_capital = []
    for ym in months:
        c = by_month_last_close.get(ym)
        if c is None or c <= 0:
            continue
        out_months.append(ym)
        out_capital.append(c / start_close)
    return out_months, out_capital


def ff5_umd_ew_unit_capital_path(months: list[str]) -> tuple[list[str], list[float]]:
    """Equal-weighted Fama-French 5-factor + UMD portfolio cumulative.

    Each month allocates 1/6 of capital to each of the six Ken French
    factor series (Mkt-RF, SMB, HML, RMW, CMA, MOM) plus the risk-free
    rate on the unallocated cash. The factor returns are already in excess
    form (long high - short low for SMB/HML/RMW/CMA/MOM; market - RF for
    Mkt-RF), so this is a zero-cost factor-portfolio overlay on top of the
    risk-free deposit. Series in percent units.
    """
    ff = _load_ff_monthly()
    cap = 1.0
    out_months = []
    out_capital = []
    cols = ["Mkt-RF", "SMB", "HML", "RMW", "CMA", "MOM"]
    for ym in months:
        if ym not in ff:
            continue
        factor_excess = sum(ff[ym][c] for c in cols) / len(cols)
        rf = ff[ym]["RF"]
        m_ret = (factor_excess + rf) / 100.0
        cap *= 1.0 + m_ret
        out_months.append(ym)
        out_capital.append(cap)
    return out_months, out_capital


def residual_alpha_cumulative(monthly_pct: dict[str, float], months: list[str]) -> tuple[list[str], list[float]]:
    """Strategy's monthly return minus its FF5+UMD factor-explained portion,
    accumulated as a $1-of-capital-equivalent cumulative growth path. This is
    the alpha trail: the part of the strategy return that the six-factor
    model cannot explain. If the regression alpha is positive and significant,
    this series grows monotonically upward.
    """
    ff = _load_ff_monthly()
    # Estimate factor loadings on the strategy's per-capital monthly return,
    # then construct strategy_monthly - (X @ beta_factors) for each month.
    # The result is alpha + residual; its cumulative sum approximates the
    # alpha trail.
    cols = ["Mkt-RF", "SMB", "HML", "RMW", "CMA", "MOM"]
    pairs = [(ym, monthly_pct[ym]) for ym in months if ym in ff and ym in monthly_pct]
    if len(pairs) < 10:
        return [], []
    y = np.array([r for _, r in pairs])
    X = np.array([[1.0] + [ff[ym][c] for c in cols] for ym, _ in pairs])
    beta = np.linalg.lstsq(X, y, rcond=None)[0]
    # Residual + intercept = alpha + epsilon; equivalently y - X[:, 1:] @ beta[1:]
    alpha_plus_eps = y - X[:, 1:] @ beta[1:]  # this still contains the intercept
    cap = 1.0
    out_months, out_capital = [], []
    for (ym, _), ape in zip(pairs, alpha_plus_eps):
        cap *= 1.0 + ape / 100.0
        out_months.append(ym)
        out_capital.append(cap)
    return out_months, out_capital


def _sharpe_from_capital(capital_path: list[float], periods_per_year: float = 12.0) -> dict:
    if len(capital_path) < 3:
        return {"sharpe": None}
    rets = np.diff(capital_path) / np.array(capital_path[:-1])
    m = float(np.mean(rets))
    s = float(np.std(rets, ddof=0))
    return {
        "n_obs": int(len(rets)),
        "monthly_mean": round(m, 6),
        "monthly_vol": round(s, 6),
        "ann_sharpe": round(m / s * (periods_per_year ** 0.5), 4) if s > 0 else None,
        "ann_mean_pct": round(100.0 * m * periods_per_year, 4),
        "ann_vol_pct": round(100.0 * s * (periods_per_year ** 0.5), 4),
        "terminal": round(capital_path[-1], 4),
    }


def main() -> int:
    strat_monthly = _load_strategy_monthly_pct()
    months_sorted = sorted(strat_monthly)

    # Strategy: explicit per-capital simulation, overlap = 4
    sim_months, sim_capital = per_capital_simulation(strat_monthly, overlap=4)
    strategy_sharpe = _sharpe_from_capital(sim_capital, periods_per_year=12.0)

    # FF5+UMD equal-weighted factor portfolio (fair quant baseline)
    ff_months, ff_capital = ff5_umd_ew_unit_capital_path(months_sorted)
    ff_sharpe = _sharpe_from_capital(ff_capital, periods_per_year=12.0)

    # Cumulative residual alpha trail (factor-adjusted return cumulative)
    # built from the per-capital monthly return series implied by the
    # explicit backtest, projected onto FF5+UMD and the residual accumulated.
    strat_monthly_per_capital = {}
    for i in range(1, len(sim_capital[:len(months_sorted)])):
        ym = months_sorted[i]
        prev = sim_capital[i-1]
        curr = sim_capital[i]
        if prev > 0:
            strat_monthly_per_capital[ym] = 100.0 * (curr / prev - 1.0)
    alpha_months, alpha_capital = residual_alpha_cumulative(strat_monthly_per_capital, months_sorted)
    alpha_sharpe = _sharpe_from_capital(alpha_capital, periods_per_year=12.0)

    print("Per-capital backtest results (unit capital = $1):")
    print(f"  Strategy (overlap=4 EW allocation):   terminal = ${sim_capital[-1]:.4f}")
    print(f"     Sharpe (monthly->ann): {strategy_sharpe['ann_sharpe']}, ann_mean = {strategy_sharpe['ann_mean_pct']}%, ann_vol = {strategy_sharpe['ann_vol_pct']}%")
    print(f"  FF5+UMD EW factor portfolio:           terminal = ${ff_capital[-1]:.4f}")
    print(f"     Sharpe (monthly->ann): {ff_sharpe['ann_sharpe']}, ann_mean = {ff_sharpe['ann_mean_pct']}%, ann_vol = {ff_sharpe['ann_vol_pct']}%")
    print(f"  Cumulative residual alpha trail:       terminal = ${alpha_capital[-1]:.4f}")
    print(f"     Sharpe (monthly->ann): {alpha_sharpe['ann_sharpe']}, ann_mean = {alpha_sharpe['ann_mean_pct']}%, ann_vol = {alpha_sharpe['ann_vol_pct']}%")

    # Write per-month series to data/. Use the final close-out cash balance
    # (with all open positions liquidated) as the terminal point so the
    # figure and the report agree on the "deployment-end" value.
    out_jsonl = DATA / "per_capital_backtest.jsonl"
    n = len(months_sorted)
    # Replace the last mark-to-market value with the close-out value.
    strat_series = list(sim_capital[:n])
    if len(sim_capital) > n:
        strat_series[-1] = sim_capital[-1]
    # Align FF EW portfolio and alpha trail to the same n-month axis as
    # strategy, padding with None where the factor data is missing.
    ff_by_ym = dict(zip(ff_months, ff_capital))
    alpha_by_ym = dict(zip(alpha_months, alpha_capital))
    with out_jsonl.open("w", encoding="utf-8") as f:
        for ym, sc in zip(months_sorted, strat_series):
            f.write(json.dumps({
                "year_month": ym,
                "strategy_capital": sc,
                "ff5umd_ew_capital": ff_by_ym.get(ym),
                "residual_alpha_capital": alpha_by_ym.get(ym),
            }) + "\n")
    print(f"\nWrote {out_jsonl}")

    REPORTS.mkdir(parents=True, exist_ok=True)
    out_json = REPORTS / "per-capital-backtest.json"
    out_json.write_text(json.dumps({
        "strategy": strategy_sharpe,
        "ff5umd_ew_portfolio": ff_sharpe,
        "residual_alpha_trail": alpha_sharpe,
        "overlap": 4,
        "tc_bps_rt": TC_BPS_RT,
        "n_monthly_obs_strategy": len(months_sorted),
    }, indent=2), encoding="utf-8")
    print(f"Report: {out_json}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
